spring:
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_ID}
    password: ${DATABASE_PASSWORD}

  jpa:
    show-sql: true
    properties:
      hibernate:
        default_batch_fetch_size: 1000
    hibernate:
      ddl-auto: create

# 포트 변경
server:
  port: 8082

# jwt.secret.key의 값은 256bit 이상이어야 합니다.
jwt:
  secret:
    key: ${SECRET_KEY}
    token-validity-in-seconds: 86400	# 초